version: '3.1'

services:
  ecommerce:
    build:
      dockerfile: dockerfile
      context: .
    environment:
      PORT: 3000
      DB_HOST: host.docker.internal
      DB_USER: yuki
      DB_PASSWORD: 1
      DB_NAME: ecommerce
    ports:
      - "3000:3000"
