version: '3.1'
services:
  postgres:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
  api:
    build:
      dockerfile: dockerfile
      context: .
    environment:
      PORT: 3000
      DB_HOST: host.docker.internal
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      DB_NAME: ${DB_DATABASE}
    ports:
      - ${APP_PORT}:${APP_PORT}
volumes:
  pg_data:
