version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: yuki
      POSTGRES_PASSWORD: 1
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
  api:
    build:
      dockerfile: dockerfile
      context: .
    environment:
      PORT: 3000
      DB_HOST: host.docker.internal
      DB_USER: yuki
      DB_PASSWORD: 1
      DB_NAME: ecommerce
    ports:
      - "3000:3000"
volumes:
  pg_data:
